### ISSUE TITLE
HTML5 API 失败时尝试自动重试

### ISSUE THREAD

**Issue by m13253** [cnbeining/Biligrab#11]
可能是因为 cache 的原因或者转码的原因，
B 站那边第一次请求一个视频的 HTML5 API 往往会返回错误。
这个时候第二次请求就有很大机率成功。

我在 BiliDan 的 https://github.com/m13253/BiliDan/commit/9f8f098259a754a04a2655d26fa79651df9024ee 中实现了它。

另外你上次贡献的那个 M3U parse 函数似乎没有实质性功能。
MPV 可以直接读 M3U，而且如果 M3U 里有时长信息反而不会每分段都要预读一次。
所以我把那个函数删掉了，用几行代码重实现了 HTML5 API。

(P.S. HTML5 API 真的很有用，小水管看 UP 主用 1080p 来坑人的视频的利器啊。)

**Comment by cnbeining** [comment]
retry个3次 实在不行 报错？

**Comment by cnbeining** [comment]
我加了个全局重试。

求测试，如果没问题就close。

**Comment by m13253** [comment]
> retry个3次 实在不行 报错？

你如果用了 HTML5 API 就知道了。
第二次如果再不行，第三次一定不会行的。
这 API 就是这德性。
只有这个 API 有这个问题，如果别的 API 也 retry 会白浪费 quota 的。

**Comment by cnbeining** [comment]
重写了下，你可以看看，好了就关issue。

**Comment by m13253** [comment]
OK 了。
关。
