### ISSUE TITLE
下载优酷等的超清

### ISSUE THREAD

**Issue by cnbeining** [cnbeining/Biligrab#12]
是的，但是&quality=4 是优酷的高清。

且不说播放器对于优酷的清晰度都不能调只能看渣清（嗯哼），就是API也不能获取超清——撑死高清。

我的办法是。。。Source设成4，用FLVCD解决。方法猥琐，但是好用。问题是不优雅。

有好的想法么？

@m13253 

（顺便召唤上你想召唤的人吧。。。集思广益）

**Comment by m13253** [comment]
> 我的办法是。。。Source设成4，用FLVCD解决。方法猥琐，但是好用。问题是不优雅。

我建议在 `--help` 菜单里写上“FLVCD 有时候能获取更高清的视频”，让用户手动启动 FLVCD。
或者发现 `quality=4` 的时候打印一条提示让用户试试 FLVCD。

总之我的想法是，不要自动开 FLVCD，而提醒用户手动换 FLVCD 就是了，一是滥用的问题，二是会员限定的视频无法解析的问题。

**Comment by cnbeining** [comment]
我可以写死这个quality，但是优酷的问题没解决。

help下个版本写一句吧。。。

继续留着issue，直到彻底解决吧。。

**Comment by m13253** [comment]
> 我可以写死这个quality，但是优酷的问题没解决。

写死 quality 干甚？
像我这样的用户用 Biligrab 的目的反而是官方播放器太高清太卡，我想要个低清版本呢。

**Comment by swordfeng** [comment]
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/youku.py
或许有帮助？
不清楚这个是否能真的弄到1080p。。。

**Comment by cnbeining** [comment]
我看过很多这东西的代码（还贡献过一些。。you-get的bilibili模块一部分是我写的），但是我在想为了youku重写下载是不是值得。。。。还是就flvcd大法好了。。。

**Comment by m13253** [comment]
you-get 的 bilibili 模块也有我的贡献呢。

但是！

you-get 的代码是在是太乱了，各种 deprecation 和死代码。（不过阅读感受比 Biligrab 好一点，因为起码遵守了 PEP8 标准）

而且，我从未听说过 you-get 能下什么高清。我曾经提 issue 想加一个 YouTube 清晰度选项却给驳回了。

**Comment by swordfeng** [comment]
http://www.bilibili.com/video/av1859634/
这个薯片的，我怎么都没弄出高清的mp4来……你们有办法吗

**Comment by cnbeining** [comment]
http://interface.bilibili.com/playurl <http://interface.bilibili.com/playurl>

<args>
<![CDATA[ uu=ab417c1571&pu=e97f80d8e1&vu=0c65fed4d5 ]]>
</args>

http://api.letvcloud.com/gpc.php? <http://api.letvcloud.com/gpc.php?>

```
<total>1</total>
<data>
<video_info>
<user_id>
<![CDATA[ 100172 ]]>
</user_id>
<video_id>
<![CDATA[ 8868931 ]]>
</video_id>
<video_name>
<![CDATA[ userup:387984 av1859634 ]]>
</video_name>
<video_duration>
<![CDATA[ 228 ]]>
</video_duration>
<media_id>
<![CDATA[ 25969036 ]]>
</media_id>
<add_time>
<![CDATA[ 2015-01-08 13:44:06 ]]>
</add_time>
<qrurl>
<![CDATA[ http://i1.letvimg.com/test/201501/08/8868931.jpg ]]>
</qrurl>
<pad>
<![CDATA[ 0 ]]>
</pad>
<play_url>
<![CDATA[ ]]>
</play_url>
<default_play>
<![CDATA[ low ]]>
</default_play>
<media>
<low>
<play_url>
<main_url>
<![CDATA[
aHR0cDovL2czLmxldHYuY24vdm9kL3YyL01USXdMekl4THpReUwySmpiRzkxWkM4eE1EQXhOekl2ZG1WeVh6QXdYekl5TFRNd01Ua3pPVFl3TWkxaGRtTXRNakk0TURrMUxXRmhZeTB4TWpnd01Ea3RNakk0TXpNekxURXdOVE0yTURZMUxUTTVaalpqTTJFeVpUbGpPRFF3TmpCbFlqQTRaalpsTWpNME5EbGlaRFl3TFRFME1qQTJPVFl3TlRZM09USXViWEEwP2I9MzY5Jm1tc2lkPTI1OTY5MDM2JnRtPTE0MjI1MDY3OTAma2V5PTU2ZWEzMWI0YjM1YjZkNDc4NGZkOGQ0ZjM5OTI2OTkzJnBsYXRpZD0yJnNwbGF0aWQ9MjAzJnBsYXlpZD0wJnRzcz1ubyZ2dHlwZT0yMSZjdmlkPTQ5MzE1NTY5NDI4JnBpcD0xODBkN2FlNDUxMjJjZjQ2ZmZiM2JmNjY0MWU4ZWNlNCZ0YWc9bW9iaWxlJnNpZ249YmNsb3VkXzEwMDE3MiZ0ZXJtaWQ9MiZwYXk9MCZvc3R5cGU9YW5kcm9pZCZod3R5cGU9dW4=
]]>
</main_url>
<backup_url_1>
<![CDATA[
aHR0cDovL2czLmxldHYuY29tL3ZvZC92Mi9NVEl3THpJeEx6UXlMMkpqYkc5MVpDOHhNREF4TnpJdmRtVnlYekF3WHpJeUxUTXdNVGt6T1RZd01pMWhkbU10TWpJNE1EazFMV0ZoWXkweE1qZ3dNRGt0TWpJNE16TXpMVEV3TlRNMk1EWTFMVE01Wmpaak0yRXlaVGxqT0RRd05qQmxZakE0WmpabE1qTTBORGxpWkRZd0xURTBNakEyT1RZd05UWTNPVEl1YlhBMD9iPTM2OSZtbXNpZD0yNTk2OTAzNiZ0bT0xNDIyNTA2NzkwJmtleT01NmVhMzFiNGIzNWI2ZDQ3ODRmZDhkNGYzOTkyNjk5MyZwbGF0aWQ9MiZzcGxhdGlkPTIwMyZwbGF5aWQ9MCZ0c3M9bm8mdnR5cGU9MjEmY3ZpZD00OTMxNTU2OTQyOCZwaXA9MTgwZDdhZTQ1MTIyY2Y0NmZmYjNiZjY2NDFlOGVjZTQmdGFnPW1vYmlsZSZzaWduPWJjbG91ZF8xMDAxNzImdGVybWlkPTImcGF5PTAmb3N0eXBlPWFuZHJvaWQmaHd0eXBlPXVu
]]>
</backup_url_1>
<backup_url_2>
<![CDATA[
aHR0cDovLzExNy4xMjEuNTQuMjE5L3ZvZC92Mi9NVEl3THpJeEx6UXlMMkpqYkc5MVpDOHhNREF4TnpJdmRtVnlYekF3WHpJeUxUTXdNVGt6T1RZd01pMWhkbU10TWpJNE1EazFMV0ZoWXkweE1qZ3dNRGt0TWpJNE16TXpMVEV3TlRNMk1EWTFMVE01Wmpaak0yRXlaVGxqT0RRd05qQmxZakE0WmpabE1qTTBORGxpWkRZd0xURTBNakEyT1RZd05UWTNPVEl1YlhBMD9iPTM2OSZtbXNpZD0yNTk2OTAzNiZ0bT0xNDIyNTA2NzkwJmtleT01NmVhMzFiNGIzNWI2ZDQ3ODRmZDhkNGYzOTkyNjk5MyZwbGF0aWQ9MiZzcGxhdGlkPTIwMyZwbGF5aWQ9MCZ0c3M9bm8mdnR5cGU9MjEmY3ZpZD00OTMxNTU2OTQyOCZwaXA9MTgwZDdhZTQ1MTIyY2Y0NmZmYjNiZjY2NDFlOGVjZTQmdGFnPW1vYmlsZSZzaWduPWJjbG91ZF8xMDAxNzImdGVybWlkPTImcGF5PTAmb3N0eXBlPWFuZHJvaWQmaHd0eXBlPXVu
]]>
</backup_url_2>
<backup_url_3>
<![CDATA[
aHR0cDovL2czLmxldHYuY24vdm9kL3YyL01USXdMekl4THpReUwySmpiRzkxWkM4eE1EQXhOekl2ZG1WeVh6QXdYekl5TFRNd01Ua3pPVFl3TWkxaGRtTXRNakk0TURrMUxXRmhZeTB4TWpnd01Ea3RNakk0TXpNekxURXdOVE0yTURZMUxUTTVaalpqTTJFeVpUbGpPRFF3TmpCbFlqQTRaalpsTWpNME5EbGlaRFl3TFRFME1qQTJPVFl3TlRZM09USXViWEEwP2I9MzY5Jm1tc2lkPTI1OTY5MDM2JnRtPTE0MjI1MDY3OTAma2V5PTU2ZWEzMWI0YjM1YjZkNDc4NGZkOGQ0ZjM5OTI2OTkzJnBsYXRpZD0yJnNwbGF0aWQ9MjAzJnBsYXlpZD0wJnRzcz1ubyZ2dHlwZT0yMSZjdmlkPTQ5MzE1NTY5NDI4JnBpcD0xODBkN2FlNDUxMjJjZjQ2ZmZiM2JmNjY0MWU4ZWNlNCZyZXRyeT0xJnRhZz1tb2JpbGUmc2lnbj1iY2xvdWRfMTAwMTcyJnRlcm1pZD0yJnBheT0wJm9zdHlwZT1hbmRyb2lkJmh3dHlwZT11bg==
]]>
</backup_url_3>
<vwidth>
<![CDATA[ 640 ]]>
</vwidth>
<vheight>
<![CDATA[ 352 ]]>
</vheight>
<gbr>
<![CDATA[ 369 ]]>
</gbr>
<storePath>
<![CDATA[
120/21/42/bcloud/100172/ver_00_22-301939602-avc-228095-aac-128009-228333-10536065-39f6c3a2e9c84060eb08f6e23449bd60-1420696056792.mp4
]]>
</storePath>
<vtype>
<![CDATA[ 21 ]]>
</vtype>
</play_url>
<definition>
<![CDATA[ 标清 ]]>
</definition>
<video_type>
<![CDATA[ MP4_350 ]]>
</video_type>
</low>
<yuanhua>
<play_url>
<main_url>
<![CDATA[
aHR0cDovL2czLmxldHYuY24vdm9kL3YyL01URXpMelEyTHprdlltTnNiM1ZrTHpFd01ERTNNaTkyWlhKZk1EQmZNakl0TXpBeE9UUTBNREEwTFdGMll5MHlNREF3TURBd0xXRmhZeTB4TWpnd01UTXRNakk0TXpBd0xUWXdPREF4T0RRMExUWmpOakExWlRJd00yWm1aVFJsWkdOaE1UUmxOR0pqWVRWaE1tUTNabU00TFRFME1qQTJPVGszTkRjNU16Y3ViWEEwP2I9MjEzMCZtbXNpZD0yNTk2OTAzNiZ0
]]>
<![CDATA[
bT0xNDIyNTA2NzkwJmtleT1kODc3MTIwYTA0NTBmN2YyOWRmZjFhNGU4ZjU5NmFkOCZwbGF0aWQ9MiZzcGxhdGlkPTIwMyZwbGF5aWQ9MCZ0c3M9bm8mdnR5cGU9MjgmY3ZpZD00OTMxNTU2OTQyOCZwaXA9MTgwZDdhZTQ1MTIyY2Y0NmZmYjNiZjY2NDFlOGVjZTQmdGFnPW1vYmlsZSZzaWduPWJjbG91ZF8xMDAxNzImdGVybWlkPTImcGF5PTAmb3N0eXBlPWFuZHJvaWQmaHd0eXBlPXVu
]]>
</main_url>
<backup_url_1>
<![CDATA[
aHR0cDovL2czLmxldHYuY29tL3ZvZC92Mi9NVEV6THpRMkx6a3ZZbU5zYjNWa0x6RXdNREUzTWk5MlpYSmZNREJmTWpJdE16QXhPVFEwTURBMExXRjJZeTB5TURBd01EQXdMV0ZoWXkweE1qZ3dNVE10TWpJNE16QXdMVFl3T0RBeE9EUTBMVFpqTmpBMVpUSXdNMlptWlRSbFpHTmhNVFJsTkdKallUVmhNbVEzWm1NNExURTBNakEyT1RrM05EYzVNemN1YlhBMD9iPTIxMzAmbW1zaWQ9MjU5NjkwMzYmdG09MTQyMjUwNjc5MCZrZXk9ZDg3NzEyMGEwNDUwZjdmMjlkZmYxYTRlOGY1OTZhZDgmcGxhdGlkPTImc3BsYXRpZD0yMDMmcGxheWlkPTAmdHNzPW5vJnZ0eXBlPTI4JmN2aWQ9NDkzMTU1Njk0MjgmcGlwPTE4MGQ3YWU0NTEyMmNmNDZmZmIzYmY2NjQxZThlY2U0JnRhZz1tb2JpbGUmc2lnbj1iY2xvdWRfMTAwMTcyJnRlcm1pZD0yJnBheT0wJm9zdHlwZT1hbmRyb2lkJmh3dHlwZT11bg==
]]>
</backup_url_1>
<backup_url_2>
<![CDATA[
aHR0cDovLzExNy4xMjEuNTQuMjE5L3ZvZC92Mi9NVEV6THpRMkx6a3ZZbU5zYjNWa0x6RXdNREUzTWk5MlpYSmZNREJmTWpJdE16QXhPVFEwTURBMExXRjJZeTB5TURBd01EQXdMV0ZoWXkweE1qZ3dNVE10TWpJNE16QXdMVFl3T0RBeE9EUTBMVFpqTmpBMVpUSXdNMlptWlRSbFpHTmhNVFJsTkdKallUVmhNbVEzWm1NNExURTBNakEyT1RrM05EYzVNemN1YlhBMD9iPTIxMzAmbW1zaWQ9MjU5NjkwMzYmdG09MTQyMjUwNjc5MCZrZXk9ZDg3NzEyMGEwNDUwZjdmMjlkZmYxYTRlOGY1OTZhZDgmcGxhdGlkPTImc3BsYXRpZD0yMDMmcGxheWlkPTAmdHNzPW5vJnZ0eXBlPTI4JmN2aWQ9NDkzMTU1Njk0MjgmcGlwPTE4MGQ3YWU0NTEyMmNmNDZmZmIzYmY2NjQxZThlY2U0JnRhZz1tb2JpbGUmc2lnbj1iY2xvdWRfMTAwMTcyJnRlcm1pZD0yJnBheT0wJm9zdHlwZT1hbmRyb2lkJmh3dHlwZT11bg==
]]>
</backup_url_2>
<backup_url_3>
<![CDATA[
aHR0cDovL2czLmxldHYuY24vdm9kL3YyL01URXpMelEyTHprdlltTnNiM1ZrTHpFd01ERTNNaTkyWlhKZk1EQmZNakl0TXpBeE9UUTBNREEwTFdGMll5MHlNREF3TURBd0xXRmhZeTB4TWpnd01UTXRNakk0TXpBd0xUWXdPREF4T0RRMExUWmpOakExWlRJd00yWm1aVFJsWkdOaE1UUmxOR0pqWVRWaE1tUTNabU00TFRFME1qQTJPVGszTkRjNU16Y3ViWEEwP2I9MjEzMCZtbXNpZD0yNTk2OTAzNiZ0bT0xNDIyNTA2NzkwJmtleT1kODc3MTIwYTA0NTBmN2YyOWRmZjFhNGU4ZjU5NmFkOCZwbGF0aWQ9MiZzcGxhdGlkPTIwMyZwbGF5aWQ9MCZ0c3M9bm8mdnR5cGU9MjgmY3ZpZD00OTMxNTU2OTQyOCZwaXA9MTgwZDdhZTQ1MTIyY2Y0NmZmYjNiZjY2NDFlOGVjZTQmcmV0cnk9MSZ0YWc9bW9iaWxlJnNpZ249YmNsb3VkXzEwMDE3MiZ0ZXJtaWQ9MiZwYXk9MCZvc3R5cGU9YW5kcm9pZCZod3R5cGU9dW4=
]]>
</backup_url_3>
<vwidth>
<![CDATA[ 1280 ]]>
</vwidth>
<vheight>
<![CDATA[ 720 ]]>
</vheight>
<gbr>
<![CDATA[ 2130 ]]>
</gbr>
<storePath>
<![CDATA[
113/46/9/bcloud/100172/ver_00_22-301944004-avc-2000000-aac-128013-228300-60801844-6c605e203ffe4edca14e4bca5a2d7fc8-1420699747937.mp4
]]>
</storePath>
<vtype>
<![CDATA[ 28 ]]>
</vtype>
</play_url>
<definition>
<![CDATA[ 原画 ]]>
</definition>
<video_type>
<![CDATA[ MP4_YUANHUA ]]>
</video_type>
</yuanhua>
</media>


<user_info>
<user_id>
<![CDATA[ 100172 ]]>
</user_id>
<user_unique>
<![CDATA[ ab417c1571 ]]>
</user_unique>
<user_key>
<![CDATA[ 7f0d2f93e5518b12f6e9287fef75c5dd ]]>
</user_key>
<user_name>
<![CDATA[ mb@bilibili.tv ]]>
</user_name>
<pay_callback>
<![CDATA[ ]]>
</pay_callback>
<video_callback>
<![CDATA[ http://api.bilibili.com/letv_cloud ]]>
</video_callback>
<status>
<![CDATA[ 1 ]]>
</status>
<limit_space>
<![CDATA[ 0 ]]>
</limit_space>
<is_autocheck>
<![CDATA[ 1 ]]>
</is_autocheck>
<watermark_flag>
<![CDATA[ 00 ]]>
</watermark_flag>
<letv_wartermark_id>
<![CDATA[ 0 ]]>
</letv_wartermark_id>
<client_wartermark_id>
<![CDATA[ 0 ]]>
</client_wartermark_id>
<default_player_id>
<![CDATA[ 0 ]]>
</default_player_id>
<video_type_set>
<![CDATA[ FLV_350,MP4_350,FLV_YUANHUA,MP4_YUANHUA ]]>


```

出来了吧。Base64编码了。

**Comment by swordfeng** [comment]
@cnbeining 原画我这里打开是404。。。两个接口的参数是？

**Comment by cnbeining** [comment]
interface.bilibili.com/playurl?&appkey=876fe0ebd0e67a0f&cid= <http://interface.bilibili.com/playurl?&appkey=876fe0ebd0e67a0f&cid=>

http://api.letvcloud.com/gpc.php?&sign=signxxxxx&cf=html5&vu=*********&ver=2.1&ran=0.6220391783863306&qr=2&format=xml&uu=leshishssb <http://api.letvcloud.com/gpc.php?&sign=signxxxxx&cf=html5&vu=*********&ver=2.1&ran=0.6220391783863306&qr=2&format=xml&uu=leshishssb>

Beining

**Comment by swordfeng** [comment]
= =我这里根本拿不到<args>栏，无论有没有sign，不知道为啥……难道还有UA限制？

**Comment by cnbeining** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

不会的。。。具体看Biligrab和letvcloudchecker的源码。。。

Beining
在 15/1/29 上午12:32, Jianfeng Zhang 写道:
>
> = =我这里根本拿不到栏，无论有没有sign，不知道为啥……难道还有UA限制？
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/cnbeining/Biligrab/issues/12#issuecomment-71971504>.
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: PGP public key: http://www.cnbeining.com/about/

iQIcBAEBCgAGBQJUycdqAAoJEJ7f0mz0/ABDNEAP/jD1v3JS0czqIlqpjYTH61Dy
4Zay7xSXHcPS2Za06gZavHCgYj3SBg1RAXvHNcoVv7/uArjp/DJtSXtCZG1eDiZu
J2arK+fQzNB9XuXIDbIbnoDoGEQmnOn0nDL+vme9tUiQpG1lbYiyqE83tSxNj5pe
A/wHKbbwZsDse6vuRJ2lQOs1EVxDBjQKg8wEydf68iAjBuh1H4cRnG5vHjdBW9d8
hGHbw3/l2tBh5ASgrLcg5mT7K7d17Wh95MhJsLixkgpHylpFD2Vv0SL+UvgBWF24
4Hfiy3SrOuQUX9FZvN1qFjcmIOMx0RdqlNBlK1SNjGogKY9zc7EF1rg5d0YOIoe+
h1RX2tJUGs66p5lu9hIzQ7oCSSGeMClBT1atCJDUEPdX5tdymfPHxNaU92YxnCaJ
pzkfoiMHjvaMHLfUrZ0fmmoQC7qVskbByYNXI4vjJMuLtXvDZnn0inLMx1rtr9Vz
jXsK7Ifb8GmEUiT7XKY1bWPvXUi4L97xxYGb9lCS8p72DyPoWbq/HCWE0eCzWk2W
pQ7Mg4xziSTEihpsORa1bVFFeeWwiU+V6leXJWLBGBFCD0RpWDHKlGTRrxYnUwgS
H2GDXqQLrAcfadz/LZh2a9/Zj+0reTGyaQoOTe0e4RqVGGpA1oEpmfZal/mC+T2W
LPXzqwv6K45bcEreSafz
=t9Lr
-----END PGP SIGNATURE-----

**Comment by swordfeng** [comment]
用biligrab开了DEBUG级别的log出来的信息里也没有\<args\>标签，无论是哪个Source
http://interface.bilibili.com/playurl?appkey=85eb6835b0a1034e&cid=2884829&quality=4&sign=6a742c1567149f546f8cb745a15e67a6
是这样的么。。。结果类似于这样
<pre>
&lt;video&gt;
&lt;result&gt;suee&lt;/result&gt;
&lt;timelength&gt;228000&lt;/timelength&gt;
&lt;format&gt;
&lt;![CDATA[ flv ]]&gt;
&lt;/format&gt;
&lt;accept_format&gt;
&lt;![CDATA[ flv ]]&gt;
&lt;/accept_format&gt;
&lt;from&gt;
&lt;![CDATA[ local ]]&gt;
&lt;/from&gt;
&lt;stream&gt;
&lt;![CDATA[ cloud ]]&gt;
&lt;/stream&gt;
&lt;seek_param&gt;
&lt;![CDATA[ start ]]&gt;
&lt;/seek_param&gt;
&lt;seek_type&gt;
&lt;![CDATA[ offset ]]&gt;
&lt;/seek_type&gt;
&lt;src&gt;0&lt;/src&gt;
&lt;durl&gt;
&lt;order&gt;1&lt;/order&gt;
&lt;length&gt;228000&lt;/length&gt;
&lt;size&gt;60738995&lt;/size&gt;
&lt;chunks&gt;950&lt;/chunks&gt;
&lt;chunksize&gt;64000&lt;/chunksize&gt;
&lt;url&gt;
&lt;![CDATA[
http://cc.acgvideo.com/201501301422/73c52770f4fc7bcbb2cdaee18aa2c04d/f/b1/2884829-1.flv
]]&gt;
&lt;/url&gt;
&lt;/durl&gt;
&lt;/video&gt;
</pre>

**Comment by cnbeining** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Wrong one!

应该是'http://interface.bilibili.com/player?' 这个。

Beining
在 15/1/30 上午1:29, Jianfeng Zhang 写道:
>
> 用biligrab开了DEBUG级别的log出来的信息里也没有<args>标签，无论是哪个Source
>
http://interface.bilibili.com/playurl?appkey=85eb6835b0a1034e&cid=2884829&quality=4&sign=6a742c1567149f546f8cb745a15e67a6
> 是这样的么。。。结果类似于这样
>
> <video>
> <result>suee</result>
> <timelength>228000</timelength>
> <format>
> <![CDATA[ flv ]]>
> </format>
> <accept_format>
> <![CDATA[ flv ]]>
> </accept_format>
> <from>
> <![CDATA[ local ]]>
> </from>
> <stream>
> <![CDATA[ cloud ]]>
> </stream>
> <seek_param>
> <![CDATA[ start ]]>
> </seek_param>
> <seek_type>
> <![CDATA[ offset ]]>
> </seek_type>
> <src>0</src>
> <durl>
> <order>1</order>
> <length>228000</length>
> <size>60738995</size>
> <chunks>950</chunks>
> <chunksize>64000</chunksize>
> <url>
> <![CDATA[
>
http://cc.acgvideo.com/201501301422/73c52770f4fc7bcbb2cdaee18aa2c04d/f/b1/2884829-1.flv
> ]]>
> </url>
> </durl>
> </video>
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/cnbeining/Biligrab/issues/12#issuecomment-72160031>.
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: PGP public key: http://www.cnbeining.com/about/

iQIcBAEBCgAGBQJUyyVJAAoJEJ7f0mz0/ABD5DwQAKWs+nelh+hW/rtdvGt+sDWp
TAz0MesXIC5LpyFLwfFlA4Afh0Xlcj215i+Jq2+V07f62u95YBhHW+JkDhRNoMH9
CtHl8AtBvLS6iGO4wMAaOhLdii0OEVRMSigfdAZYX8PKxhJU44vLpjwuUFf9qO6U
x+X4WLRetDgORH30ZIi/2IXuJWjh3PUa5Rqqnu5/l0hFH99offj3vLQDkYa10Ycv
q4UEHEPGrBRrgTvyJrgARv1jc5vIL7axl4QS0vQ5Wx0iYXC7sZgcjOA/UYQKSWVd
z23mxLoKfRyx8LucCj4fV6xvLR4l19nbpdm7q29ClYp6wWwAXYFqKpjxibxdHEOk
ASyVHlsUg4/v5r/o95xnwe+ahdlOqZIxo/yBc4vMiQJNZPLxbljo0bHdnQEydHDq
0noc5g0kLrOqUUUtdWJXbYstMG0KPCtXPwr3nyjVNNiDTs48wboVngQ+XV0UeMMt
RHpLt3xpG+ri3NOVBBZnpfPZ0QIkjumsp+bM4uLCN74hdg+6iM7QPo16qpb4jkOJ
5dlZvgqjU2AP2gwzmbV595uSOz1oDPQ+v5pFfUtEXc5T81yxqI3KtveT4bFuykLF
V5QLP+YhkvK1hbry94RA9lk4T8AXtkoLYosOoSIjDRWbIXRiKZqcOlEcfqAjgo4b
A9Ln1iFtWWe2nwCX8nkm
=/LeL
-----END PGP SIGNATURE-----

**Comment by swordfeng** [comment]
换成player, 继续没有找到。。。
<pre>
&lt;ip&gt;120.84.11.38&lt;/ip&gt;
&lt;country&gt;中国&lt;/country&gt;
&lt;isp&gt;联通&lt;/isp&gt;
&lt;login&gt;true&lt;/login&gt;
&lt;name&gt;swordfeng [中国]&lt;/name&gt;
&lt;user&gt;445430&lt;/user&gt;
&lt;scores&gt;3170&lt;/scores&gt;
&lt;money&gt;168.8&lt;/money&gt;
&lt;face&gt;http://i2.hdslb.com/user/4454/445430/myface.jpg&lt;/face&gt;
&lt;pwd&gt;undefined&lt;/pwd&gt;
&lt;isadmin&gt;false&lt;/isadmin&gt;
&lt;permission&gt;10000,1001&lt;/permission&gt;
&lt;time&gt;1422600564&lt;/time&gt;
&lt;rank&gt;10000&lt;/rank&gt;
&lt;level&gt;正式会员&lt;/level&gt;
&lt;shot&gt;false&lt;/shot&gt;
&lt;suggest_comment&gt;false&lt;/suggest_comment&gt;
&lt;maxlimit&gt;1500&lt;/maxlimit&gt;
&lt;chatid&gt;2884829&lt;/chatid&gt;
&lt;server&gt;chat.bilibili.com&lt;/server&gt;
&lt;vtype&gt;letv&lt;/vtype&gt;
&lt;aid&gt;1859634&lt;/aid&gt;
&lt;typeid&gt;46&lt;/typeid&gt;
&lt;pid&gt;1&lt;/pid&gt;
&lt;click&gt;86991&lt;/click&gt;
&lt;favourites&gt;4215&lt;/favourites&gt;
&lt;credits&gt;0&lt;/credits&gt;
&lt;coins&gt;606&lt;/coins&gt;
&lt;fw_click&gt;15350&lt;/fw_click&gt;
&lt;duration&gt;3:48&lt;/duration&gt;
&lt;arctype&gt;Original&lt;/arctype&gt;
&lt;danmu&gt;1252&lt;/danmu&gt;
&lt;bottom&gt;0&lt;/bottom&gt;
&lt;sinapi&gt;1&lt;/sinapi&gt;
&lt;acceptguest&gt;true&lt;/acceptguest&gt;
&lt;acceptaccel&gt;false&lt;/acceptaccel&gt;
</pre>

**Comment by cnbeining** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

如果是乐视源，你需要解析到乐视的返回，才能有vu。

Beining
在 15/1/30 上午1:56, Jianfeng Zhang 写道:
>
> 换成player, 继续没有找到。。。
>
> <ip>120.84.11.38</ip>
> <country>中国</country>
> <isp>联通</isp>
> <login>true</login>
> <name>swordfeng [中国]</name>
> <user>445430</user>
> <scores>3170</scores>
> <money>168.8</money>
> <face>http://i2.hdslb.com/user/4454/445430/myface.jpg</face>
> <pwd>undefined</pwd>
> <isadmin>false</isadmin>
> <permission>10000,1001</permission>
> <time>1422600564</time>
> <rank>10000</rank>
> <level>正式会员</level>
> <shot>false</shot>
> <suggest_comment>false</suggest_comment>
> <maxlimit>1500</maxlimit>
> <chatid>2884829</chatid>
> <server>chat.bilibili.com</server>
> <vtype>letv</vtype>
> <aid>1859634</aid>
> <typeid>46</typeid>
> <pid>1</pid>
> <click>86991</click>
> <favourites>4215</favourites>
> <credits>0</credits>
> <coins>606</coins>
> <fw_click>15350</fw_click>
> <duration>3:48</duration>
> <arctype>Original</arctype>
> <danmu>1252</danmu>
> <bottom>0</bottom>
> <sinapi>1</sinapi>
> <acceptguest>true</acceptguest>
> <acceptaccel>false</acceptaccel>
>
> —
> Reply to this email directly or view it on GitHub
<https://github.com/cnbeining/Biligrab/issues/12#issuecomment-72161785>.
>

-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0.22 (Darwin)
Comment: PGP public key: http://www.cnbeining.com/about/

iQIcBAEBCgAGBQJUyyupAAoJEJ7f0mz0/ABDqQcQALtyb2S7OJbBHyl/rdKV8H77
l+A7+TpaJqhzWa6p9shSh5Jc8qiQh6Cvv5KqtIw+GUcGMUh24lHloeogmYYckN5Y
kQsCgic3L2jicSgAm3uMfXMcSz6Huo/Sf9W/b2+BUo3NiBhEz66RGM1xV/8dTuiV
kr9KOiYnL0L2BYpMk0+SVCq5dd6lzNVA8EmOI6SeT6d3HNfngvMAI/0R3obnPLFo
+pmPGnl+Xxy5IXmooFuSdGD4luN6BoWqYMh20Lrrv1MwmDMgqqUcQ2U6YGUR5YvF
m4aZWf3GylY4ImjSSuenv1sNfp/WOYknnaYGAjVZfl3soXqfN6kqe8WdFJiEKOvg
8Wc45APeFZPctBWnFRt8yB4PKcvkuyhFvaVagKxfcYoUb8bci7bZOCd+rGgMvlsf
N9xBbw3o3gGbtNlD62I+gT8H7iFe9v+Zv52OLvvYGzI/+pNU7ohE1DH7OfWHtg+a
fDokDlnUhcj2c5Z0LaspQR3iDGqfp4T/ZxPR09GBEy6aZItARdpf+hx5HJ+uaFGl
IhOfbot0uYALbLxQJX6EciwoKnoqjWFs0I/XCEvAZ3zBvjHoZU3T7Jwp2H5kTWQZ
FlL+BQrr1jrGHYWYFRK12pa0ajoahR6JDaQfzGgMQsJ5OH0dRAxLWxr6PiStKY5S
e1dLA2EJy6HWnBPrWTZI
=aowx
-----END PGP SIGNATURE-----

**Comment by cnbeining** [comment]
Shut it for now.
