### ISSUE TITLE
Opening 20 concurrent connections with axel/aria2 is acturally not that fast

### ISSUE THREAD

**Issue by m13253** [cnbeining/Biligrab#15]
使用 Axel/Aria2 并发下载的时候，并发连接数设置为 20 并不能提升下载速度。

我的 WiFi 网络很慢，在开了 20 个并发连接之后，反而没有下载速度了。Wiresharks 抓包显示，网络带宽被 TCP 重传的开销占满了。

建议实际做实验测试一下多少个并发连接是效率最高的，不能得不偿失。
或者默认 4（Axel 的默认），开个配置接口让用户可以改成想要的数字。

**Comment by cnbeining** [comment]
（锐速大法好

恩，也好，开个地方让人自己调。

我的环境是ping高但是带宽也高，共享带宽，所以往死里抢。当然不是永远适合。。。
