### ISSUE TITLE
Fail to convert xml danmaku to ass via danmaku2ass2

### ISSUE THREAD

**Issue by persmule** [cnbeining/Biligrab#18]
When convert xml danmaku to ass via danmaku2ass2 on Debian GNU/Linux Stretch, it reports:

Traceback (most recent call last):
  File "../danmaku2ass2.py", line 40, in <module>
    gettext.install('danmaku2ass', os.path.join(os.path.dirname(os.path.abspath(os.path.realpath(sys.argv[0] or 'locale'))), 'locale'))
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 11: ordinal not in range(128)

danmaku2ass (3) works with no problem.

**Comment by cnbeining** [comment]
Known issue.

I would recommend that you get in touch with the developer directly to dig
into this issue.

Beining

2015年9月1日星期二，persmule <notifications@github.com> 写道：

**Comment by m13253** [comment]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 11: ordinal not in range(128)

你没有设置系统语言，而 Danmaku2ASS 的主程序放在了含有特殊字符（如中文）的路径下了。
解决方法有两个：

1. 设置系统语言，中文或英文皆可。编码（如果询问）填 UTF-8。
2. 把程序放到英文字符的路径下。

如果还是无法解决，请发上来 `locale` 命令的输出。

**Comment by cnbeining** [comment]
Close for now.
