### ISSUE TITLE
biligrab fail to call danmaku2ass.

### ISSUE THREAD

**Issue by persmule** [cnbeining/Biligrab#19]
On my box, biligrab fail to call danmaku2ass and report:

...
ERROR:root:Danmaku2ASS failed: global name 'Danmaku2ASS' is not defined
        Head to https://github.com/m13253/danmaku2ass/issues to complain about this.
Traceback (most recent call last):
  File "./biligrab.py", line 698, in convert_ass_py2
    Danmaku2ASS(xml_name, filename + '.ass', resolution[0], resolution[1],
NameError: global name 'Danmaku2ASS' is not defined
...

I place danmaku2ass2.py at the same directory of bilidan.py, and called from the same directory.

**Comment by cnbeining** [comment]
请将```danmaku2ass.py```保持这个名字，放在和Biligrab同一个目录下。

**Comment by cnbeining** [comment]
Please reopen should happens again.
