### ISSUE TITLE
不加任何参数的交互模式无法下载av965891 p47，然而加-l fail.log反而就能下载了

### ISSUE THREAD

**Issue by Icenowy** [cnbeining/Biligrab#22]

**Comment by Icenowy** [comment]
icenowy [ Biligrab@master ] $ ./biligrab.py 
av965891
P47
Source?
INFO:root:Oversea not set, use original API(methon 0).
WARNING:root:Cannot read cookie, may affect some videos...
INFO:root:Downloading part 47 ...
INFO:root:Fetching api to read video info...
INFO:root:cid is 1396656
INFO:root:partname is 47集 火山疗伤
INFO:root:Title is 虹猫蓝兔七侠传2006 (1 108)
INFO:root:Total pages is 108
INFO:root:Fetching XML...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39270  100 39270    0     0   159k      0 --:--:-- --:--:-- --:--:--  159k
INFO:root:The XML file, 47 - 47集 火山疗伤.xml should be ready...enjoy!
INFO:root:Finding video location...
INFO:root:Trying to get download URL...
ERROR: Biligrab failed: not well-formed (invalid token): line 1, column 0
       If you think this should not happen, please dump your log using "-l", and open a issue ar https://github.com/cnbeining/Biligrab/issues .
       Make sure you delete all the sensive data before you post it publicly.
Traceback (most recent call last):
  File "./biligrab.py", line 1373, in <module>
    main(vid, p, oversea, cookies, download_software, concat_software, is_export, probe_software, danmaku_only, time_fetch, download_thread, thread_single_download)
  File "./biligrab.py", line 937, in main
    rawurl = get_video(oversea, convert_m3u = False)
  File "./biligrab.py", line 560, in get_video
    rawurl = find_video_address_normal_api(cid, BILIGRAB_HEADER, oversea, convert_m3u)
  File "./biligrab.py", line 500, in find_video_address_normal_api
    dom = parseString(data)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by Icenowy** [comment]
icenowy [ Biligrab@master ] $ ./biligrab.py -l fail.log
av965891
P47
Source?
WARNING:root:Cannot read cookie, may affect some videos...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39270  100 39270    0     0   186k      0 --:--:-- --:--:-- --:--:--  187k
初始化下载: http://video.dispatch.tc.qq.com/T0010kvOuuh.mp4?vkey=57C09BC338BFAEE00AD30D9654223A6CD572BBBAC893184A36FB29BDD5BF7D4DA82E552FF4BA7AC8A06B585D96AC8717120C718B42D0B57A3F1BA0C6958090D5FDD4ACC0868B6E6664AF7F16CCC92211770C5466AC93FD7B&br=75097&platform=1&fmt=mp4&level=0&type=mp4
文件大小: 1159995 字节
打开输出文件 0.flv
开始下载
（省略）
1.1 Megabyte 已下载，用时 11 秒。（95.84 千字节/秒）
ffmpeg version 2.8 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.3 (GCC) 20150626 (AOSC OS, Core)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-runtime-cpudetect --enable-shared --enable-swresample --enable-vdpau --enable-version3 --enable-x11grab
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1bf1c60] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'ff.txt':
  Duration: N/A, start: 0.000000, bitrate: 550 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x480, 502 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc
    Metadata:
      creation_time   : 2012-08-08 06:32:49
      handler_name    : GPAC ISO Video Handler
    Stream #0:1(und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 48 kb/s
    Metadata:
      creation_time   : 2012-08-08 06:32:50
      handler_name    : GPAC ISO Audio Handler
[mp4 @ 0x1bf8f20] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x1bf8f20] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to '47 - 47集 火山疗伤.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0(und): Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 640x480, q=2-31, 502 kb/s, 25 fps, 25 tbr, 25k tbn, 25k tbc
    Metadata:
      creation_time   : 2012-08-08 06:32:49
      handler_name    : GPAC ISO Video Handler
    Stream #0:1(und): Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 48 kb/s
    Metadata:
      creation_time   : 2012-08-08 06:32:50
      handler_name    : GPAC ISO Audio Handler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  404 fps=0.0 q=-1.0 Lsize=    1096kB time=00:00:16.12 bitrate= 556.9kbits/s    
video:991kB audio:95kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.984453%

**Comment by Icenowy** [comment]
另外自带的danmaku2ass在没有开-l的时候也不能工作

**Comment by cnbeining** [comment]
1. -l 不是这么用的。。。看readme

2. danmaku2ass问题不能复现。。。

3. 我真不知道您好这口（

```
python b2.py -l DEBUG 
av965891
P47
Source?
DEBUG:root:FAKE IP: 0 
DEBUG:root:av_list
INFO:root:Oversea not set, use original API(methon 0).
DEBUG:root:!!!!!!!!!!!!!!!!!!!!!!!
WARNING: This log contains some sensive data. You may want to delete some part of the data before you post it publicly!
!!!!!!!!!!!!!!!!!!!!!!!
DEBUG:root:BILIGRAB_HEADER
!!!!!!!!!!!!!!!!!!!!!!!
WARNING: This log contains some sensive data. You may want to delete some part of the data before you post it publicly!
!!!!!!!!!!!!!!!!!!!!!!!
=======================DUMP DATA==================
{
  "ip": "142.1.29.***",
  "hostname": "wifihost-29-***.wireless.utsc.utoronto.ca",
  "city": "Toronto",
  "region": "Ontario",
  "country": "CA",
  "loc": "43.6629,-79.3987",
  "org": "AS239 University of Toronto",
  "postal": "M5S"
}
========================DATA END==================
DEBUG: [965891]
INFO:root:Downloading part 47 ...
DEBUG:root:ffmpeg, aria2c
DEBUG:root:BiliURL: https://api.bilibili.com/view?appkey=85eb6835b0a1034e&id=965891&page=47&type=xml&sign=8fe0d382dc62de994c3a108b4277d3bd
INFO:root:Fetching api to read video info...
DEBUG:root:<?xml version="1.0" encoding="UTF-8"?>
<info>
  <tid>32</tid>
  <typename>完结动画</typename>
  <play>707877</play>
  <review>3794</review>
  <video_review>233916</video_review>
  <favorites>9696</favorites>
  <title> 虹猫蓝兔七侠传2006 (1-108)</title>
  <allow_bp>0</allow_bp>
  <allow_feed>0</allow_feed>
  <allow_download>1</allow_download>
  <description>企鹅 国产良心之一，看过感觉不错，没人搬.。
低俗弹幕请举报。
有问题的私信或@。（第一集OP最后一集ED）</description>
  <tag>TV动画,虹猫蓝兔七侠传,童年,自古红蓝出CP,童年回忆,国产动画,良心,虹猫蓝兔系列,国产良心,童年系列</tag>
  <pic>http://i1.hdslb.com/u_user/099620a9c84ffea8bc811bf8e72b7afa.jpg</pic>
  <author>听竹喧</author>
  <mid>217724</mid>
  <face>http://i2.hdslb.com/user/2177/217724/myface.jpg</face>
  <pages>108</pages>
  <instant_server>chat.bilibili.com</instant_server>
  <created>1392429126</created>
  <created_at>2014-02-15 09:52</created_at>
  <credit>865</credit>
  <coins>1038</coins>
  <spid></spid>
  <src>c</src>
  <cid>1396656</cid>
  <partname>47集 火山疗伤</partname>
  <offsite>http://share.acg.tv/flash.swf?aid=965891&amp;amp;page=47</offsite>
</info>

DEBUG:root:Bilibili API: <?xml version="1.0" encoding="UTF-8"?>
<info>
  <tid>32</tid>
  <typename>完结动画</typename>
  <play>707877</play>
  <review>3794</review>
  <video_review>233916</video_review>
  <favorites>9696</favorites>
  <title> 虹猫蓝兔七侠传2006 (1-108)</title>
  <allow_bp>0</allow_bp>
  <allow_feed>0</allow_feed>
  <allow_download>1</allow_download>
  <description>企鹅 国产良心之一，看过感觉不错，没人搬.。
低俗弹幕请举报。
有问题的私信或@。（第一集OP最后一集ED）</description>
  <tag>TV动画,虹猫蓝兔七侠传,童年,自古红蓝出CP,童年回忆,国产动画,良心,虹猫蓝兔系列,国产良心,童年系列</tag>
  <pic>http://i1.hdslb.com/u_user/099620a9c84ffea8bc811bf8e72b7afa.jpg</pic>
  <author>听竹喧</author>
  <mid>217724</mid>
  <face>http://i2.hdslb.com/user/2177/217724/myface.jpg</face>
  <pages>108</pages>
  <instant_server>chat.bilibili.com</instant_server>
  <created>1392429126</created>
  <created_at>2014-02-15 09:52</created_at>
  <credit>865</credit>
  <coins>1038</coins>
  <spid></spid>
  <src>c</src>
  <cid>1396656</cid>
  <partname>47集 火山疗伤</partname>
  <offsite>http://share.acg.tv/flash.swf?aid=965891&amp;amp;page=47</offsite>
</info>

INFO:root:cid is 1396656
INFO:root:partname is 47集 火山疗伤
INFO:root:Title is 虹猫蓝兔七侠传2006 (1 108)
INFO:root:Total pages is 108
INFO:root:Fetching XML...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39270  100 39270    0     0  22373      0  0:00:01  0:00:01 --:--:-- 30703
INFO:root:The XML file, 47 - 47集 火山疗伤.xml should be ready...enjoy!
INFO:root:Finding video location...
INFO:root:Trying to get download URL...
INFO:root:http://interface.bilibili.com/playurl?appkey=85eb6835b0a1034e&cid=1396656&sign=76b7fe69e541c4e5385fc7c7105116c1
DEBUG:root:<?xml version="1.0" encoding="UTF-8"?>
<video>
	<result>suee</result>
	<timelength>722219</timelength>
	<from><![CDATA[qq]]></from>
	<src>30</src>
	<durl>
		<order>1</order>
		<length>722219</length>
		<size>54236714</size>
		<url><![CDATA[http://video.dispatch.tc.qq.com/T0010kvOuuh.mp4?vkey=61B5D4916CD028109FE45DEA6689FBCD3438FBAA940508374E241465CC55604DC2D16DB93EB34591A50EB4BC804E8DBFB9A291857D7110EC187EA3E18DC3B444CE9A5DF094968EB4120E5A4763B46B61B387171456E51086&br=75097&platform=1&fmt=mp4&level=0&type=mp4]]></url>
		<backup_url>
		<url><![CDATA[http://122.228.215.142/vkp.tc.qq.com/T0010kvOuuh.mp4?vkey=61B5D4916CD028109FE45DEA6689FBCD3438FBAA940508374E241465CC55604DC2D16DB93EB34591A50EB4BC804E8DBFB9A291857D7110EC187EA3E18DC3B444CE9A5DF094968EB4120E5A4763B46B61B387171456E51086&br=75097&platform=1&fmt=mp4&level=0&type=mp4]]></url>
		<url><![CDATA[http://122.228.215.143/vkp.tc.qq.com/T0010kvOuuh.mp4?vkey=61B5D4916CD028109FE45DEA6689FBCD3438FBAA940508374E241465CC55604DC2D16DB93EB34591A50EB4BC804E8DBFB9A291857D7110EC187EA3E18DC3B444CE9A5DF094968EB4120E5A4763B46B61B387171456E51086&br=75097&platform=1&fmt=mp4&level=0&type=mp4]]></url>
		</backup_url>
	</durl>
</video>
INFO:root:1 videos in part 47 to download, fetch yourself a cup of coffee...
INFO:root:Downloading #0...
DEBUG:root:aria2c -c -U "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.52 Safari/537.36" -s16 -x16 -k1M --out 0.flv "http://video.dispatch.tc.qq.com/T0010kvOuuh.mp4?vkey=61B5D4916CD028109FE45DEA6689FBCD3438FBAA940508374E241465CC55604DC2D16DB93EB34591A50EB4BC804E8DBFB9A291857D7110EC187EA3E18DC3B444CE9A5DF094968EB4120E5A4763B46B61B387171456E51086&br=75097&platform=1&fmt=mp4&level=0&type=mp4"
[#664c62 0.9MiB/1.1MiB(90%) CN:1 DL:72KiB ETA:1s]                                                                                  
11/07 08:56:07 [NOTICE] Download complete: /Users/Beining/Movies/虹猫蓝兔七侠传2006 (1 108)/0.flv

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
664c62|OK  |    54KiB/s|/Users/Beining/Movies/虹猫蓝兔七侠传2006 (1 108)/0.flv

Status Legend:
(OK):download completed.
DEBUG:root:file '/Users/Beining/Movies/虹猫蓝兔七侠传2006 (1 108)/0.flv'

INFO:root:Concating videos...
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --arch=x86_64 --enable-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f9034025200] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from 'ff.txt':
  Duration: N/A, start: 0.000000, bitrate: 550 kb/s
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x480, 502 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc
    Stream #0:1: Audio: aac (HE-AAC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 48 kb/s
[mp4 @ 0x7f9035002c00] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x7f9035002c00] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to '47 - 47集 火山疗伤.mp4':
  Metadata:
    encoder         : Lavf56.36.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 640x480, q=2-31, 502 kb/s, 25 fps, 25 tbr, 25k tbn, 25k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 48 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  404 fps=0.0 q=-1.0 Lsize=    1097kB time=00:00:16.17 bitrate= 555.6kbits/s    
video:991kB audio:95kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.984598%
INFO:root:Done, enjoy yourself!
INFO:root:Converting danmaku to ASS file with danmaku2ass(py2)...
INFO:root:Trying to get resolution...
DEBUG:root:Software: ffprobe, resolution [640, 480]
INFO:root:Resolution is 640x480
INFO:root:INFO: The ASS file should be ready!
INFO:root:Part Done!

```

**Comment by Icenowy** [comment]
@cnbeining 加上-l DEBUG之后问题又不能复现了OOOrz
（不对似乎我Biligrab有点老。。。待我git pull，我错了

**Comment by Icenowy** [comment]
新版本没有问题了，我错了
还有我在回味童年呢~
