### ISSUE TITLE
强烈要求处理好编码问题

### ISSUE THREAD

**Issue by harry159821** [cnbeining/Biligrab#24]
在寻找优雅使用B站的各种非浏览器用法的时候找到了这里，
于是试着在 Windows GBK，即 sys.stdout.encoding = "cp936" 的环境下测试
发现文件乱码，于是查看代码，发现以下写法：
```
reload(sys)
sys.setdefaultencoding('utf-8')
```
作为一枚 Pythoner 强烈抵制这种写法
在Python27的环境下应该全部使用 Unicode 编码，而代码文件则使用 Utf-8 存储

其他推荐写法：
```
在你目前的代码上添加
os.system(command.decode("utf-8").encode(sys.stdout.encoding))
title = title.decode("utf-8")
```
```
或者全部使用 Unicode 后使用
os.system(command.encode(sys.stdout.encoding))
```

**Comment by cnbeining** [comment]
好吧因为我从未在Windows下测试过（

我个人是写3出身的，虽然2.7越来越多。

为了保留贡献记录，建议您发个PR。

**Comment by cnbeining** [comment]
Close as #25 .
